development:
  secret_key_base: 'XXX'
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:  <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_twiml_app_sid: <%= ENV["TWILIO_TWIML_APP_SID"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>

test:

production:
  secret_key_base: 'XXX'
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:  <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_twiml_app_sid: <%= ENV["TWILIO_TWIML_APP_SID"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
